server:
  port: ${AUTH_SERVER_PORT:9000}

spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: ${JWT_ISSUER_URI}}
        client:
          storage-service:
            registration:
              client-id: storage-service
              client-secret: "{noop}${AUTH_CLIENT_SECRET:secret}"
              client-name: Storage Service
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - api.read
                - api.write